Name: "ALPHA"

Port: 7070

StellarAssetCode: "INRT"

StellarSeeds:
  Source: "SAFDGVVDPRXYEME4PPQ5T65LHAP3WXFSOIZR7SXI4TZL2ZZEIRMNZG2Z"
  Issuer: "SCH5KFKOE2C5NQHMF32P4PZL2Z25TJTWNBKM3NB2AFBWVOQJALZPP63Z"
  Distributor: "SBSQ3D5IEIHK6LY6CYR4GDRGNPVCMYIJ6ULZI6IQ7APCIFKFWGVCS3XU"

StellarAddresses:
  Source: "GBVFKNGJE2TJFG26KRSDNGPDRLADOKMAY33ZLRP2FCLOEE22BWFGDNZM"
  Issuer: "GCFSHL57TI7ZPHEMLP4WMVI24WIWHJBFH74MZYA6IIZEVS3JFVDHYOBL"
  Distributor: "GDGDRDMRMW22LM2AAX5NM4TGVN3BOJUEOWAIVHHW2HLG2SQWU37UY73U"

DBconnectionParams:
  Host: "localhost"
  Port: 5432
  User: "sbiadmin"
  Password: "sbiadmin339"
  DbName: "sbi"

BankPoolAccID: "123456789ALPHAPOOL123456789"