Name: "ALPHA"

Port: 7070

StellarAssetCode: "INRT"

StellarSeeds:
  Source: "SCAHN7ZATNS46YROQNKLXMZYAP4WPVBMI7EI4SRTPUJCVBZQP3UC6SEJ"
  Issuer: "SBXTQ35DXH74ASLASYPJVYNBPAYXMVS2FKEYM7HHSUEM3SAOGSQVNOK5"
  Distributor: "SA6BGTMZRKQBJFKQWGTK5SEDKPKHJNLC2QFYCNW57NLEZVEPAAKUGMEY"

StellarAddresses:
  Source: "GDDYE2UF5TUMGTQITWPXGWN3IKBNEELZG6H3TRGBHRASZALXF4DLCQHM"
  Issuer: "GCDGBZLCMYOAQH4ACRDJ7LKN6MODMICBPW4TPMBKKBIBPJRZL2SLZJ2R"
  Distributor: "GALRIXDRLNMOAUOQLNEFC5TJ5Q4M5WW7WLVOIJRJAGFNJBQHJMJMS635"

DBconnectionParams:
  Host: "localhost"
  Port: 5432
  User: "sbiadmin"
  Password: "sbiadmin339"
  DbName: "sbi"

BankPoolAccID: "123456789ALPHAPOOL123456789"