Name: "BETA"

Port: 6060

StellarAssetCode: "USDT"

StellarSeeds:
  Source: "SASYB3QFL3RSGBWG5B63PB73GDAXPS2X6RCJEIOIHVDQGEBD2PXS7EO2"
  Issuer: "SC4G66NFWVZLACXVFL333NBLPDZPRNMELAEF3754FDJYIXLTXBV4RFAM"
  Distributor: "SDDV427O7AW5COCXBAN6MUVCFI6ME66D4GV4JXRXDALVJQWT5LN3DEVK"

StellarAddresses:
  Source: "GCNLJPDG7PYA5LL5FTFC2L5CYVJSYTEDRIBEF3ZCL5Y4Y3JPYH3OV5C4"
  Issuer: "GCWIVZO6ZQHCZBIOHGLHAML7RZTJ77HIFGRU46ZVEAYMPBFYHWCGMYO6"
  Distributor: "GAJPTAGSHHH5ZSRCEZIQTYHXZZSOUTKAV7342ONN4DQVGY7PR2TDE2BP"

DBconnectionParams:
  host: "localhost"
  port: 5432
  user: "jpmadmin"
  password: "jpmadmin339"
  dbName: "jpm"

BankPoolAccID: "987654321BETAPOOL987654321"