Name: "JP MORGAN"
Port: 6060
StellarSeeds:
  Source: "SB7SZBJ5BUYWQGQZ3TVSTDN7FY7F6ERPFI22TBJRDBYHOKUDRVLG4KFW"
  Issuer: "SBJW3HMQG4AUCFO63YGNCBJRQAODMGOOQBLQT74TBSUYHYPDU56WZB3V"
  Distributor: "SDZ2T2L4LT76MIPUIA5LJLYGPDSF4CWIWVID5U32H6N62N5OEZ2VSTBX"
StellarAddresses:
  Source: "GC6DWJNRAGCRIT5HOHLEFGMM4HXLWUYTKQYGDS6EXS3BIK4H2PZFK76Z"
  Issuer: "GDT3YKELD54PFY6XAC42BQGBPSL5XBS3XC4XYUKHYSKEEEMW53AYCQUV"
  Distributor: "GCG2S7CUX4VWXNW5LL3V7CGD36ZBV6TED43LN4B772M5JQ7Z7I43SEOT"