Name: "JP MORGAN"

Port: 6060

StellarAssetCode: "JPMT"

StellarSeeds:
  Source: "SDD6C7TGJMW6MFWJOYVJDK6G6ZUNSU5TBFI5BW7FB2DRCEWEWA7QROMB"
  Issuer: "SDMGKWCYJTJ63VCUU6MMUWNNFUVPYA7F4RHIRQRYR33B52GFNIQRACXG"
  Distributor: "SCTEILPRMP3WFWMIYZA7YBKYDQXEKBMDNBRTTHIIDBL3C5U7I4XPRR4D"

StellarAddresses:
  Source: "GB7LGAHWN23VU2ENXEVIABCKQKVYAJGQF5GA2E5JTWBGXHTNTG3RYIPO"
  Issuer: "GBJC7ACZTIPW75BUR5X37T5FC626G27MDR3QZSKNZLC3CRD4XCDIRQKZ"
  Distributor: "GDT674D4C5SFIUK7I5XVHOPSR7RC72ODKXQUHGNINVOLFJ32HYAEVQBS"

DBconnectionParams:
  host: "localhost"
  port: 5432
  user: "jpmadmin"
  password: "jpmadmin339"
  dbName: "jpm"

BankPoolAccID: "987654321JPMORGANPOOL987654321"