Name: "SBI"
Port: 7070
StellarSeeds:
  Source: "SBNSSMFUYGUIPXMOEKSAGD524THQKE6S5NUEGZVZ3LNB422G427DNAIL"
  Issuer: "SBZK7WTUPFIY55HRRW4SYH2KFZVMLH7STS2PTQHOW4RAF7UWRB74BGKM"
  Distributor: "SDP3446MMEKWDSUKJ65GASOBNL6L42UVBPAXKKGOMCSVARB3WMLHJVQY"
StellarAddresses:
  Source: "GAB3VYCOG4AG7IDXIYV5K3BQM77OK335GX5HI4PE3Z3YDFFYFPJB4LSF"
  Issuer: "GDLRZ55JMQ2XUR5ELYVJTHPSPQWR2PJTYEX7HMMXI43AQWGUYM2QKKVZ"
  Distributor: "GC2JUDOWWCREXJPNGCL4IFBF6C6EVFVEHBSJWQT26T6A63TWIIOYQZQH"