Banks:
- BankName: "ALPHA"
  BankPoolAccID: "123456789ALPHAPOOL123456789"
  Database:
    Host: "localhost"
    Port: 5432
    User: "sbiadmin"
    Password: "sbiadmin339"
    DbName: "sbi"

- BankName: "BETA"
  BankPoolAccID: "987654321BETAPOOL987654321"
  Database:
    Host: "localhost"
    Port: 5432
    User: "jpmadmin"
    Password: "jpmadmin339"
    DbName: "jpm"